default = true

[servers]
default = "factorio"
autostart = false

[servers.example]
address = "127.0.0.1"
game = "factorio"
port = 4312

[auth]
platform = [
    "Twitch",
    "YouTube",
]

[auth.twitch]
username = ""
client_id = ""
client_secret = ""

[auth.youtube]
username = ""
api_token = ""
