---
config:
    theme: dark
    class:
        hideEmptyMembersBox: true
        nodeSpacing: 200
        rankSpacing: 200
        useMaxWidth: true

---
classDiagram
    direction RL
    Command "0..*" <|--|> "0..*" Runner
    Runner  <|--|> Integration
    Command <|--|> "0..*" GameServerTrigger
    GameServerTrigger <|--|> Trigger
    GameServerTrigger <|--|> GameServer

    class GameServer
    class Command
    class Trigger
    class Runner
    class Integration
    class GameServerTrigger
